# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.MyUser'),
        ),
    ]
